### ISSUE TITLE
Expire with NX option

### ISSUE THREAD

**Issue by kerhong** [HeyPuter/kv.js#1]
Saw your project on https://news.ycombinator.com/item?id=35608601 and the `expires` command seems wrong

https://github.com/HeyPuter/kv.js/blob/596ba10368a88f414b89784d9ae59c5106bf4f04/README.md?plain=1#L119-L120

Shouldn't `kv.expire('username', 120, 'NX');` mean "Set expirity of `username` to 60 seconds if it has no expirity"? The documentation suggests "Set expirity of `username` to 60 seconds **if `username` does not exist**" which makes no sense (as the key does not exist and thus can't have expirity).

See redis docs for reference/suggestion https://redis.io/commands/expire/

**Comment by jelveh** [comment]
Thank you for reporting this. You are correct, this is a mistake.
