### ISSUE TITLE
i did not understand the usage

### ISSUE THREAD

**Issue by ama-coder** [HeyPuter/kv.js#5]
hello.
what is the use of this lib? i didn't understand properly.
(whats the difference between this and a simple value/variable in js?)

**Comment by jelveh** [comment]
I'd characterize the use case as "in-memory caching module for JavaScript for when you need caching but running Redis or Memcached would be an overkill."
This is what I needed for puter.com (rate limiting etc.) so I decided to build it. 
Hope this helps :)

**Comment by ama-coder** [comment]
thanks, are you iranian? can you explain to me in farsi. 'cause i didn't get it any ay....

**Comment by jelveh** [comment]
It stores data in memory. I don't think we'll ever add persistence to disk (or maybe we will if users ask for it!)
Sorry, I don't have a Farsi keyboard and I wouldn't be able to explain it in Farsi very well.

**Comment by ama-coder** [comment]
tnx!
