### ISSUE TITLE
Create Typescript typings

### ISSUE THREAD

**Issue by touhidrahman** [HeyPuter/kv.js#7]
NPM packages nowadays are developed using Typescript and type definitions are exported from the library so that methods and classes are typed. Since this library is entirely written in javascript, one of the following two can be picked to provide type definitions:

1. Convert the library to typescript and export interfaces
2. Submit type definitions to [definitely typed repository](https://github.com/DefinitelyTyped/DefinitelyTyped) so that consumers can add optional typings using `npm install -D @types/heyputer__kvjs`

Personally, and I believe most others as well, would like to see no. 1 picked and this library converted into a typescript one.

**Comment by ama-coder** [comment]
could you provide more info

**Comment by jelveh** [comment]
Closed by #9
